[[bond]]
source = "tpknam1qzc9ng07thdwsxpukqtudv8xqdullqzy38nlfckqtgc2eqkscj57yq80stp"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "30"

[bond.signatures]
tpknam1qzc9ng07thdwsxpukqtudv8xqdullqzy38nlfckqtgc2eqkscj57yq80stp = "signam1qqfua5vjpt3y5nhjs9gp8jhmd9aqedwa05hj5j69lzfj5alww5ktw9gvrj0q4ydmkzwf5ehssvnkz669a4rty9t4qg6tm3aew2l9fhqw4l43ea"
